import { notFound } from "next/navigation";
import FormatLegalPool from "../../../components/FormatLegalPool";
import { FORMATS, formatBySlug, relatedFormatsBySlug } from "../../../lib/seoContent";
export function generateStaticParams() { return FORMATS.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }) { const { slug } = await params; const format = formatBySlug(slug); if (!format) return { title: "Format Not Found", robots: { index: false, follow: true } }; return { title: `${format.name} Pokémon Draft Format`, description: `${format.summary} Learn how ${format.name} works for a Pokémon draft league.`, alternates: { canonical: `/formats/${slug}` } }; }
export default async function FormatPage({ params }) {
  const { slug } = await params; const format = formatBySlug(slug); if (!format) notFound(); const relatedFormats = relatedFormatsBySlug(slug);
  const schema = { "@context": "https://schema.org", "@type": "WebPage", name: `${format.name} Pokémon Draft Format`, description: format.summary, url: `https://www.draftcentral.gg/formats/${slug}`, breadcrumb: { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "DraftCenter", item: "https://www.draftcentral.gg/" }, { "@type": "ListItem", position: 2, name: "Formats", item: "https://www.draftcentral.gg/formats" }, { "@type": "ListItem", position: 3, name: format.name, item: `https://www.draftcentral.gg/formats/${slug}` }] } };
  return <main className="seo-article-shell format-detail-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><nav className="public-page-nav"><a className="quiet-button" href="/formats">← All formats</a><a className="quiet-button" href="/guides">Guides</a><a className="quiet-button" href="/pokemon">Pokédex</a></nav><article><header><span className="eyebrow">DRAFTCENTER FORMAT</span><h1>{format.name}</h1><p className="seo-article-intro">{format.subtitle}</p></header><section><h2>Format overview</h2><p>{format.summary}</p></section><FormatLegalPool format={format} /><section><h2>Using this format in a draft league</h2><p>DraftCenter applies the format’s base legal pool when a commissioner selects it. Commissioners can still set roster size, draft method, point budget, pick timers, transactions, playoffs, and league-specific bans or price overrides.</p></section><section><h2>Legality and pricing</h2><p>Historical legality follows the supported competitive definition for this ruleset. Curated tier values are used where DraftCenter has a format-specific price source; uncovered Pokémon use the documented fallback pricing model until more league data is available.</p></section><section><h2>Community evidence</h2><p>Pokémon profile pages report eligibility-aware draft rate and ADP by format, along with auction samples, teammate patterns, and confirmed match results aggregated across DraftCenter leagues.</p><a className="secondary-button inline-link-button" href="/pokemon">Research Pokémon in the Pokédex</a></section><aside className="seo-next-step"><h2>Related Pokémon draft formats</h2><p>Compare nearby rulesets before choosing the legal pool for your league.</p><div className="pokemon-tags">{relatedFormats.map((related) => <a key={related.slug} href={`/formats/${related.slug}`}>{related.name}</a>)}</div></aside><aside className="seo-next-step"><h2>Run a {format.name} league</h2><p>Create a league, choose this format during setup, review the generated pool, and publish the league when you are ready for coaches or spectators.</p><a className="primary-button inline-link-button" href="/">Open DraftCenter</a></aside></article></main>;
}
