export const GUIDES = {
  "what-is-pokemon-draft-league": {
    title: "How a Pokémon Draft League Works",
    description: "A friendly walkthrough of Pokémon draft leagues, from choosing a format and drafting unique rosters to weekly matches, transactions, standings, and playoffs.",
    intro: "If you are new to draft leagues, the easiest way to picture one is as a season with your own Pokémon roster. You and the other coaches draft from the same pool, so no two teams are alike. Then you prepare for one opponent at a time, make roster moves when you need them, and try to earn a place in the playoffs. Here is what that looks like in practice—and where DraftCenter helps along the way.",
    sections: [
      ["First, the commissioner chooses the kind of league", "Every league needs a shared answer to a few basics: Which game or generation are we using? Is this singles or doubles? Which Pokémon and special mechanics are legal? How large is each roster? These choices shape everything that follows, so they should be visible before anyone commits to a team.", "In DraftCenter, the commissioner creates the league and works through Setup. They choose a supported format or a custom pool, then review roster limits, special mechanics, access, and league-specific bans before inviting everyone."],
      ["Then everyone drafts a different roster", "This is the part that makes a draft league feel special. Once one coach selects a Pokémon, it is normally gone for everyone else. A snake draft moves through a pick order that reverses each round. An auction lets coaches decide how much of a shared budget each Pokémon is worth.", "DraftCenter's live draft room shows the available pool, whose turn it is, the timer, each roster, and the rules that still apply. Coaches can prepare a private queue beforehand; the queue helps with planning but never reserves a Pokémon."],
      ["A good roster needs jobs, not just big names", "Favorites are part of the fun, but a roster also has to function for an entire season. Coaches usually look for different speed tiers, physical and special damage, defensive answers, disruption, recovery, and Pokémon that can fill more than one role. The goal is not one perfect team—it is enough options to build a new team every week.", "Use DraftCenter's Pokédex to compare typing, base stats, abilities, versioned move pools, and format eligibility. The public profile pages also show draft rate, ADP, auction samples, and teammate patterns when enough league data exists."],
      ["Each week is a new puzzle", "You do not bring your whole roster into every battle. You study the next opponent, decide which threats matter most, and build a legal battle team from your drafted Pokémon. That opponent-by-opponent preparation is the heart of draft play: a Pokémon that barely appeared last week might be the key to this week's matchup.", "The Schedule shows the opponent and deadline. Either participating manager can report the result afterward, and the saved result updates the league record and standings. Managers can also share a Twitch or YouTube match from League Home if they want spectators."],
      ["Standings turn separate matches into a season", "Wins and losses are only part of the picture. Leagues often use game differential or remaining-Pokémon differential when records are tied. The important thing is not choosing one universal system; it is agreeing on the order before the season so nobody has to invent a rule during the playoff race.", "DraftCenter calculates the standings from reported results using the league's configured tiebreakers. Commissioners can review or correct results, while coaches can see the same current table from the league."],
      ["Transactions let a roster grow with the season", "Sometimes a draft plan does not work, a matchup exposes a hole, or another coach proposes a trade that helps both teams. Free-agent moves and trades keep the season flexible, but limits and deadlines should apply equally to everyone.", "DraftCenter keeps trades, add/drop moves, and queued claims in Transactions. The commissioner sets the limits and processing schedule; managers submit moves there so the official roster and its history stay together."],
      ["The season ends with playoffs and an archive", "The best regular-season teams advance to a bracket, where every matchup is elimination pressure. When a champion is decided, the season should become a record everyone can revisit—not a collection of messages that disappears over time.", "DraftCenter builds the playoff bracket from the league's settings and stores the champion, standings, rosters, results, awards, transactions, and bracket when the commissioner ends the season. A new season can begin without erasing the completed one."],
    ],
    links: [
      ["Compare snake and auction drafts", "/guides/snake-vs-auction-pokemon-draft"],
      ["Build a draft tier list", "/guides/pokemon-draft-tier-list-guide"],
      ["Browse supported formats", "/formats"],
      ["Explore public leagues", "/leagues"],
      ["Open commissioner manuals", "/manuals/commissioner"],
    ],
  },
  "how-to-run-pokemon-draft-league": {
    title: "How to Run a Pokémon Draft League: A Commissioner’s Walkthrough",
    description: "A practical, step-by-step walkthrough for setting up a Pokémon draft league, inviting coaches, running the draft, managing the season, and crowning a champion.",
    intro: "Running a league can look intimidating because there are a lot of small decisions. You do not need to solve all of them at once. Start with the experience you want your group to have, test the setup with a few people, and use DraftCenter's readiness checks to catch the details before draft day. This walkthrough follows the same order you will use in the product.",
    sections: [
      ["Create the league before you perfect the rules", "Give the league a clear name and season label, decide whether it is private, public to watch, or open to join, and add a description that tells coaches what they are signing up for. A practice league is useful when you want to learn the controls without adding results to career statistics.", "Select Start a new league from DraftCenter. You can invite a small test group first and adjust most settings later from Commissioner Tools and Setup."],
      ["Work through Setup in a sensible order", "Choose the format and legal pool first, then the draft method, roster size, prices or points, timers, transactions, standings, and playoffs. Test the numbers against your actual team count. A rule that works for eight teams may leave too few useful Pokémon for sixteen.", "DraftCenter's Setup workspace keeps these choices together. The Commissioner Launch Checklist shows what is configured, claimed, posted, backed up, and ready. If you price many Pokémon at once, use the downloadable Pricing Template and review the proposed changes before confirming them."],
      ["Invite people and make ownership obvious", "Send each coach a manager invitation and ask them to claim the correct team well before the draft. Add a co-commissioner if someone else will help with rulings or scheduling. Spectator access should stay separate from permissions that can change league data.", "Create expiring Manager or Spectator links from Commissioner Tools. Co-commissioners can help operate the league, while only the primary commissioner can transfer ownership or delete it."],
      ["Treat draft readiness like a real preflight check", "A few minutes of checking can save an hour of draft-night confusion. Confirm the team count, claimed teams, legal pool, roster limits, budget or points, draft order, timer, and official start time. Tell everyone what happens if a coach misses a pick or loses connection.", "The draft setup screen reports readiness problems directly. Start manually when everyone is present, or use scheduled automatic start only after DraftCenter says the league is ready. Save a recovery backup before the draft."],
      ["Let the regular season run from one record", "Publish the schedule, remind coaches how to report results, and keep roster moves in the official transaction flow. Make the deadline policy clear, but leave room for reasonable extensions when both coaches communicate early.", "Schedule, reported results, standings, trades, free agency, claims, and the League Board stay connected in DraftCenter. A league Discord channel can receive selected announcements, while personal Discord alerts remain each member's choice."],
      ["Handle problems consistently and leave a paper trail", "You will eventually face a late match, mistaken result, unavailable coach, or unclear rule. Pause, check what the published rule says, and use the same remedy you would use for another team. If the rule is genuinely missing, explain the decision and add it for the future.", "Use the League Board for durable rulings. The yellow Help button opens the commissioner manual, and Get help with this league can send a direct support request with optional safe diagnostics. Recovery history is available when a supported restore is truly needed."],
      ["Close the season before starting the next one", "Confirm the final standings and playoff results, celebrate the champion, and make sure the record is complete. Only then should you roll the league forward.", "End season freezes the champion, rosters, results, bracket, awards, transactions, and standings in the archive. Download a final spreadsheet or backup, review the archive, and then start the next season."],
    ],
    links: [["Open the full commissioner manual", "/manuals/commissioner"], ["Compare snake and auction", "/guides/snake-vs-auction-pokemon-draft"], ["Browse formats", "/formats"]],
  },
  "snake-vs-auction-pokemon-draft": {
    title: "Snake or Auction? Choosing Your Pokémon Draft Style",
    description: "Choose between snake and auction drafting by comparing the experience for coaches, roster strategy, draft-day pacing, budgets, and commissioner setup.",
    intro: "There is no universally better draft style. Snake drafts make turns and availability the main puzzle. Auctions make value and budget management the puzzle. The best choice is the one your group will enjoy understanding and playing for an entire draft night—not the one that sounds most advanced.",
    sections: [
      ["Choose snake when you want the easiest draft to follow", "Coaches take one Pokémon at a time in an order that reverses each round. The reversal helps balance early and late positions, while long gaps between turns reward backup plans. New coaches usually understand the room quickly because every turn has one clear decision.", "Select Snake in Setup, choose the roster limits and timer, and confirm the order. During the live draft, DraftCenter shows the current coach, upcoming order, available Pokémon, rosters, and each coach's private queue."],
      ["Choose auction when your group enjoys prices and tradeoffs", "Coaches nominate Pokémon and bid from equal starting budgets. Everyone can chase the same favorite, but winning an expensive star means having less to spend on the rest of the roster. Auctions create wonderfully different team shapes, though every coach has to pay attention throughout the room.", "Select Auction in Setup, then review the starting budget, roster limits, nomination flow, bid rules, and Pokémon prices. DraftCenter prevents a winning bid from leaving a coach unable to complete a legal roster."],
      ["The preparation feels different", "Snake preparation is about tiers, pick gaps, and predicting what might survive until your next turn. Auction preparation is about price ranges, fallback options, and knowing when to stop bidding. In either format, a list with several acceptable answers is safer than falling in love with one exact roster.", "Coaches can build a private queue in DraftCenter. Commissioners can use the Pricing Template for bulk auction or point values, then preview every proposed change before saving it."],
      ["Think about the people running the room", "Snake drafts tend to move faster and are easier when coaches may briefly step away between turns. Auctions need more active attention, clearer bid timing, and a commissioner who is comfortable explaining edge cases. A first-time league is often happier starting simple.", "Create a Practice league and run a short mock draft with the real settings. You can test the room without affecting career statistics or risking the official season."],
      ["Our practical recommendation", "Use snake when the group wants an approachable night with predictable turns. Use auction when most coaches enjoy valuation and want the freedom to compete for any Pokémon. If the group is split, choose the format that the least experienced coaches can confidently explain back to you.", "Whichever option you choose, do not start until the DraftCenter readiness messages are clear and every manager has claimed the correct team."],
    ],
    links: [["Read the commissioner walkthrough", "/guides/how-to-run-pokemon-draft-league"], ["Build a league tier list", "/guides/pokemon-draft-tier-list-guide"], ["Open the commissioner manual", "/manuals/commissioner"]],
  },
  "pokemon-draft-tier-list-guide": {
    title: "How to Build a Pokémon Draft Tier List That Fits Your League",
    description: "Build and maintain a practical Pokémon draft tier list using your exact format, useful roles, scarcity, roster math, and transparent league evidence.",
    intro: "A draft tier list is really a pricing tool for one specific league. It is not a universal ranking of which Pokémon are best. The same Pokémon can be a bargain in one format and a poor fit in another because the legal pool, battle style, mechanics, roster size, and available alternatives all changed. Start with your league—not somebody else's finished list.",
    sections: [
      ["Lock the format before you rank anything", "Write down the game, generation, singles or doubles rules, legal mechanics, clauses, and excluded Pokémon. Move pools and abilities change between games. A list built for a different ruleset may look polished while being wrong for the league you are about to run.", "Choose the format in DraftCenter first and inspect the generated legal pool. League-specific bans and overrides can still be added, but the selected format should remain the starting source of truth."],
      ["Price the jobs a Pokémon can do repeatedly", "Ask what a Pokémon contributes across many opponents. Reliable speed control, defensive utility, positioning, recovery, strong neutral damage, and several believable sets tend to matter more than one spectacular matchup. Pokémon that cover several jobs can free the rest of the roster to specialize.", "Use the DraftCenter Pokédex to check stats, typing, abilities, format eligibility, and game-specific move pools without mixing data from different games."],
      ["Scarcity matters as much as raw strength", "If ten legal Pokémon can fill a role, coaches have alternatives. If only two can provide a certain speed tier, typing, redirection option, weather ability, or Restricted answer, those options may deserve a premium. Pricing should reflect what becomes difficult to replace after the draft begins.", "Filter the legal pool and compare nearby alternatives before assigning a value. On public profiles, common teammates and format-specific ADP can help you notice combinations, but only when the displayed sample is meaningful."],
      ["Check the roster math", "Multiply the league size by the minimum roster size and make sure every price band has enough choices. Then build a few sample rosters under the actual budget or point cap. If every sensible roster has the same shape, the list may be forcing coaches instead of creating decisions.", "DraftCenter's Setup warnings help catch pool, roster, and budget conflicts. Use a Practice league or mock draft to see whether viable choices remain late in the room."],
      ["Use data as evidence, not an answer key", "Draft rate, ADP, auction price, and match record can show where coaches value a Pokémon or where a price may be off. They cannot prove that one Pokémon caused a team's record. Always keep the sample size and eligible formats beside the number.", "DraftCenter profile pages display eligibility-aware draft rate and ADP, auction samples, teammate patterns, and confirmed-match results. Small samples are labeled so commissioners can combine them with judgment instead of treating them as a verdict."],
      ["Change the list slowly and explain why", "After the season, look for Pokémon that repeatedly went undrafted, disappeared much earlier than expected, or produced extreme auction prices across several rooms. Make a small adjustment, record the reason, and keep the old version. Coaches trust a list more when they can understand how it evolved.", "Export the current pricing before a major revision. For bulk updates, fill the Pricing Template's new value or rank column, upload it, review every proposed change, and confirm only when the preview matches your intention."],
    ],
    links: [["Explore the Pokémon catalog", "/pokemon"], ["Browse supported formats", "/formats"], ["Open the commissioner manual", "/manuals/commissioner"]],
  },
};

export const FORMATS = [
  ["national-dex", "National Dex", "All supported generations, forms, and Mega Evolutions", "A complete DraftCenter pool for cross-generation draft leagues, with commissioner-controlled bans, costs, Restricted Pokémon limits, and Mega limits."],
  ["reg-mb", "Regulation M-B", "Pokémon Champions VGC · June 17–September 2, 2026", "The current Pokémon Champions regulation with Mega Evolution available and a curated DraftCenter legal pool."],
  ["reg-ma", "Regulation M-A", "Pokémon Champions VGC · April 8–June 17, 2026", "The opening Pokémon Champions regulation and its original competitive legal pool."],
  ["reg-a", "Regulation A", "Scarlet & Violet VGC · January 2023", "The initial Paldea format, excluding Paradox Pokémon, Treasures of Ruin, and box legends."],
  ["reg-b", "Regulation B", "Scarlet & Violet VGC · February–March 2023", "Expanded Regulation A with Paradox Pokémon joining the legal pool."],
  ["reg-c", "Regulation C", "Scarlet & Violet VGC · April–June 2023", "Added the Treasures of Ruin while keeping box legends unavailable."],
  ["reg-d", "Regulation D", "Scarlet & Violet VGC · July–September 2023", "Opened the format to many Pokémon transferred through Pokémon HOME."],
  ["reg-e", "Regulation E", "Scarlet & Violet VGC · October 2023–January 2024", "Added the Kitakami Pokédex and Teal Mask options."],
  ["reg-f", "Regulation F", "Scarlet & Violet VGC · January–April 2024", "Added the Indigo Disk and Blueberry Pokédex pool without Restricted legends."],
  ["reg-g", "Regulation G", "Scarlet & Violet VGC · May–August 2024", "Introduced one Restricted Pokémon per team."],
  ["reg-h", "Regulation H", "Scarlet & Violet VGC · September 2024–January 2025", "A lower-power format excluding most Legendary and Paradox Pokémon."],
  ["reg-i", "Regulation I", "Scarlet & Violet VGC · May–August 2025", "Allowed up to two Restricted Pokémon per team."],
  ["reg-j", "Regulation J", "Scarlet & Violet VGC · September 2025–January 2026", "Expanded the two-slot Restricted category to include Mythical Pokémon."],
  ["swsh-series9", "Sword & Shield Series 9", "Sword & Shield VGC · May–July 2021", "A broad Generation 8 pool without Restricted or Mythical Pokémon."],
  ["swsh-series13", "Sword & Shield Series 13", "Sword & Shield VGC · September–October 2022", "The final Generation 8 ruleset with unrestricted Legendary and Mythical access."],
  ["sm-vgc2018", "VGC 2018", "Ultra Sun & Ultra Moon VGC", "A Generation 7 National Pokédex-style pool without Restricted or Mythical Pokémon."],
  ["custom", "Custom Draft Format", "Commissioner-defined legality and pricing", "Build a legal pool, bans, costs, mechanics, and roster restrictions for a bespoke league."],
].map(([slug, name, subtitle, summary]) => ({ slug, name, subtitle, summary }));

export function formatBySlug(slug) {
  return FORMATS.find((format) => format.slug === slug);
}
