-- Source-attributed competitive Pokemon usage snapshots.
-- These observations never alter DraftCenter regulation legality or pricing.

create table public.competitive_formats (
  id text primary key check (id ~ '^[a-z0-9-]{2,80}$'),
  name text not null check (char_length(name) between 2 and 120),
  battle_style text not null check (battle_style in ('singles', 'doubles')),
  ruleset_family text not null check (ruleset_family in ('vgc', 'smogon', 'other')),
  generation smallint not null check (generation between 1 and 20),
  regulation_id text,
  source_format_id text not null check (char_length(source_format_id) between 2 and 120),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.competitive_datasets (
  id bigint generated by default as identity primary key,
  format_id text not null references public.competitive_formats(id) on delete restrict,
  source_name text not null check (char_length(source_name) between 2 and 80),
  source_url text not null check (source_url ~ '^https://'),
  period_start date not null,
  period_end date not null check (period_end >= period_start),
  rating_cutoff integer not null default 0 check (rating_cutoff between 0 and 9999),
  total_battles bigint check (total_battles is null or total_battles >= 0),
  methodology text not null check (char_length(methodology) between 10 and 500),
  source_sha256 text not null check (source_sha256 ~ '^[a-f0-9]{64}$'),
  imported_at timestamptz not null default now(),
  unique (format_id, source_name, period_start, period_end, rating_cutoff)
);

create table public.pokemon_competitive_snapshots (
  dataset_id bigint not null references public.competitive_datasets(id) on delete cascade,
  pokemon_key text not null check (pokemon_key ~ '^[a-z0-9-]{1,100}$'),
  pokemon_name text not null check (char_length(pokemon_name) between 1 and 120),
  rank integer not null check (rank > 0),
  weighted_usage numeric(9,6) not null check (weighted_usage between 0 and 100),
  raw_uses bigint not null check (raw_uses >= 0),
  raw_usage numeric(9,6) not null check (raw_usage between 0 and 100),
  real_uses bigint check (real_uses is null or real_uses >= 0),
  real_usage numeric(9,6) check (real_usage is null or real_usage between 0 and 100),
  primary key (dataset_id, pokemon_key),
  unique (dataset_id, rank)
);

create index pokemon_competitive_snapshots_key_idx
  on public.pokemon_competitive_snapshots (pokemon_key, dataset_id);
create index competitive_datasets_latest_idx
  on public.competitive_datasets (format_id, period_end desc, rating_cutoff desc);

alter table public.competitive_formats enable row level security;
alter table public.competitive_datasets enable row level security;
alter table public.pokemon_competitive_snapshots enable row level security;

revoke all on public.competitive_formats from public, anon, authenticated;
revoke all on public.competitive_datasets from public, anon, authenticated;
revoke all on public.pokemon_competitive_snapshots from public, anon, authenticated;
grant all on public.competitive_formats to service_role;
grant all on public.competitive_datasets to service_role;
grant all on public.pokemon_competitive_snapshots to service_role;
revoke all on sequence public.competitive_datasets_id_seq from public, anon, authenticated;
grant usage, select on sequence public.competitive_datasets_id_seq to service_role;

create or replace function public.get_public_pokemon_competitive_profile(p_pokemon_key text)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with requested as (
    select lower(regexp_replace(coalesce(p_pokemon_key, ''), '[^a-zA-Z0-9]+', '-', 'g')) as pokemon_key
  ), latest_datasets as (
    select distinct on (d.format_id)
      d.id, d.format_id, d.source_name, d.source_url, d.period_start,
      d.period_end, d.rating_cutoff, d.total_battles, d.methodology
    from public.competitive_datasets d
    join public.competitive_formats f on f.id = d.format_id and f.is_active
    order by d.format_id, d.period_end desc, d.rating_cutoff desc, d.id desc
  ), observations as (
    select
      f.id as format_id, f.name as format_name, f.battle_style,
      f.ruleset_family, f.generation, f.regulation_id,
      s.pokemon_name, s.rank, s.weighted_usage, s.raw_uses,
      s.raw_usage, s.real_uses, s.real_usage,
      d.source_name, d.source_url, d.period_start, d.period_end,
      d.rating_cutoff, d.total_battles, d.methodology
    from requested r
    join public.pokemon_competitive_snapshots s on s.pokemon_key = r.pokemon_key
    join latest_datasets d on d.id = s.dataset_id
    join public.competitive_formats f on f.id = d.format_id
    order by
      case f.ruleset_family when 'vgc' then 0 when 'smogon' then 1 else 2 end,
      f.battle_style, s.rank
    limit 12
  )
  select coalesce(jsonb_agg(to_jsonb(observations)), '[]'::jsonb) from observations;
$$;

revoke execute on function public.get_public_pokemon_competitive_profile(text) from public;
grant execute on function public.get_public_pokemon_competitive_profile(text) to anon, authenticated;
