import { notFound } from "next/navigation";
import GuideCopyBlock from "../../../components/GuideCopyBlock";
import { GUIDES, GUIDE_PUBLISHED_DATE, GUIDE_UPDATED_DATE } from "../../../lib/seoContent";

function displayDate(value) {
  return new Date(`${value}T12:00:00Z`).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" });
}

export function generateStaticParams() { return Object.keys(GUIDES).map((slug) => ({ slug })); }
export async function generateMetadata({ params }) {
  const { slug } = await params; const guide = GUIDES[slug];
  if (!guide) return { title: "Guide Not Found", robots: { index: false, follow: true } };
  return { title: guide.title, description: guide.description, alternates: { canonical: `/guides/${slug}` }, openGraph: { type: "article", title: guide.title, description: guide.description, url: `/guides/${slug}` } };
}
export default async function GuidePage({ params }) {
  const { slug } = await params; const guide = GUIDES[slug]; if (!guide) notFound();
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "Article", headline: guide.title, description: guide.description, datePublished: GUIDE_PUBLISHED_DATE, dateModified: GUIDE_UPDATED_DATE, author: { "@type": "Organization", name: "DraftCenter Editorial Team", url: "https://www.draftcentral.gg/about#editorial-standards" }, publisher: { "@id": "https://www.draftcentral.gg/#organization" }, mainEntityOfPage: `https://www.draftcentral.gg/guides/${slug}` }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "DraftCenter", item: "https://www.draftcentral.gg/" }, { "@type": "ListItem", position: 2, name: "Guides", item: "https://www.draftcentral.gg/guides" }, { "@type": "ListItem", position: 3, name: guide.title, item: `https://www.draftcentral.gg/guides/${slug}` }] }] };
  return <main className="seo-article-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><nav className="public-page-nav"><a className="quiet-button" href="/guides">← All guides</a><a className="quiet-button" href="/formats">Formats</a><a className="quiet-button" href="/">DraftCenter Home</a></nav><article><header><span className="eyebrow">A PRACTICAL DRAFTCENTER GUIDE</span><h1>{guide.title}</h1><p className="seo-article-intro">{guide.intro}</p><p className="guide-byline">Written and reviewed by the <a href="/about#editorial-standards">DraftCenter Editorial Team</a> · Published {displayDate(GUIDE_PUBLISHED_DATE)} · Updated {displayDate(GUIDE_UPDATED_DATE)}</p></header>{guide.answer ? <aside className="guide-direct-answer"><span className="eyebrow">SHORT ANSWER</span><h2>{guide.title}</h2><p>{guide.answer}</p></aside> : null}{guide.sections.map(([heading, body, draftCenter]) => <section key={heading}><h2>{heading}</h2><p>{body}</p>{draftCenter ? <div className="guide-feature-callout"><h3>How this works in DraftCenter</h3><p>{draftCenter}</p></div> : null}</section>)}{guide.template ? <GuideCopyBlock {...guide.template} /> : null}{guide.checklist?.length ? <section className="guide-launch-checklist"><span className="eyebrow">QUICK CHECK</span><h2>{guide.checklistTitle || "Before you continue"}</h2><ul>{guide.checklist.map((item) => <li key={item}>{item}</li>)}</ul></section> : null}<section className="guide-source-note"><h2>How this guide is maintained</h2><p>DraftCenter reviews this guide against the product's current workflows. See <a href="/about#data-methodology">our data methodology</a> and <a href="/about#editorial-standards">editorial standards</a>, including how to report a correction.</p></section>{guide.links?.length ? <aside className="seo-next-step"><h2>Where to go next</h2><div className="pokemon-tags">{guide.links.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</div></aside> : null}<aside className="seo-next-step"><h2>Ready to try it?</h2><p>You can explore public leagues and Pokémon without an account. Sign in when you are ready to create a league, join a team, or put one of these workflows into practice.</p><a className="primary-button inline-link-button" href="/">Open DraftCenter</a></aside></article></main>;
}
