import PokemonDirectory from "../../components/PokemonDirectory";

export const metadata = { title: "Pokédex and Pokémon Draft Statistics", description: "Search Pokémon by name, type, generation, color, Egg Group, shape, ability, stats, moves, format legality, and DraftCenter draft results.", alternates: { canonical: "/pokemon" } };

const featuredPokemon = ["pikachu", "charizard", "garchomp", "incineroar", "rillaboom", "flutter-mane", "urshifu-single-strike", "ogerpon", "calyrex", "miraidon", "koraidon", "dragonite"];

export default function PokemonPage() {
  return <><PokemonDirectory /><nav className="explore-card pokemon-index-links" aria-label="Pokémon profile indexes"><h2>Browse every Pokémon profile</h2><p>Use the interactive Pokédex above or follow crawlable profile indexes organized for quick research. Type and generation indexes help compare broad groups, while color, Egg Group, and body-shape indexes are useful for themed teams and Nuzlocke rules. Each profile brings the species facts together with DraftCenter draft activity, format eligibility, common teammates, and competitive results when enough public data is available.</p><p>Start with the A–Z directory when you know the name, or choose a category when you want to discover alternatives for a roster slot. The interactive view can combine several filters before you open a detailed profile.</p><div className="pokemon-tags"><a href="/pokemon/a-z">All profiles A–Z</a><a href="/pokemon/types">Browse by type</a><a href="/pokemon/generations">Browse by generation</a><a href="/pokemon/colors">Browse by color</a><a href="/pokemon/egg-groups">Browse by Egg Group</a><a href="/pokemon/shapes">Browse by shape</a><a href="/nuzlocke">Track a Nuzlocke Run</a><a href="/pokedex-tracker">Start a Pokédex Tracker</a></div><h3>Popular Pokémon draft profiles</h3><div className="pokemon-tags">{featuredPokemon.map((name) => <a key={name} href={`/pokemon/${name}`}>{name.split("-").map((word) => `${word[0].toUpperCase()}${word.slice(1)}`).join(" ")}</a>)}</div></nav></>;
}
