"use client";

import { useEffect, useState } from "react";
import { createClient } from "../lib/supabase/client";
import LeagueHub from "./LeagueHub";
import PokemonDraftLeague from "./PokemonDraftLeague";

const inputStyle = { padding: 11, borderRadius: 8, border: "1px solid #46517c", background: "#080c1c", color: "#fff", width: "100%" };
const authPanel = { width: "min(430px, calc(100vw - 32px))", padding: 28, borderRadius: 16, border: "1px solid #2a3157", background: "#11162b", boxShadow: "0 20px 70px rgba(0, 0, 0, .38)" };

function ProfileSetup({ supabase, user, onSaved }) {
  const [username, setUsername] = useState(""); const [displayName, setDisplayName] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function save(event) { event.preventDefault(); setBusy(true); const { data, error } = await supabase.from("profiles").update({ username, display_name: displayName.trim() }).eq("id", user.id).select("id, display_name, username").single(); setBusy(false); if (error) return setMessage(error.message); onSaved(data); }
  return <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 16, background: "radial-gradient(circle at top, #1d2857, #080b18 55%)" }}><section style={authPanel}><div style={{ color: "#ffd23f", fontSize: 13, fontWeight: 800, letterSpacing: 1.5 }}>DRAFTCENTER</div><h1 style={{ margin: "10px 0 6px" }}>Choose your coach profile</h1><p style={{ color: "#aeb7dc", lineHeight: 1.45 }}>This is your site-wide identity. Your team name can be different in every league.</p><form onSubmit={save} style={{ display: "grid", gap: 13 }}><label>Display name<input value={displayName} onChange={(e) => setDisplayName(e.target.value)} required minLength={2} style={inputStyle} placeholder="Bobby" /></label><label>Username<input value={username} onChange={(e) => setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, ""))} required minLength={3} maxLength={24} style={inputStyle} placeholder="bobbydrafts" /><small style={{ color: "#aeb7dc" }}>3–24 lowercase letters, numbers, or underscores.</small></label>{message && <p style={{ margin: 0, color: "#ffd66b" }}>{message}</p>}<button className="primary-button" disabled={busy}>{busy ? "Saving..." : "Continue to DraftCenter"}</button></form></section></main>;
}

function LeagueTools({ league, onClose, onUpdated }) {
  const [supabase] = useState(() => createClient()); const [name, setName] = useState(league.name || ""); const [season, setSeason] = useState(league.season_label || ""); const [description, setDescription] = useState(league.description || ""); const [startsAt, setStartsAt] = useState(league.draft_starts_at ? new Date(league.draft_starts_at).toISOString().slice(0, 16) : ""); const [isPublic, setIsPublic] = useState(false); const [invite, setInvite] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  if (league.role !== "commissioner" && league.role !== "co_commissioner") return null;
  async function saveDetails(event) { event.preventDefault(); setBusy(true); const { data, error } = await supabase.rpc("update_league_details", { p_league_id: league.id, p_name: name, p_description: description, p_season_label: season, p_draft_starts_at: startsAt ? new Date(startsAt).toISOString() : null, p_is_public: isPublic }); if (error) { setBusy(false); return setMessage(error.message); } let reminderMessage = ""; if (startsAt) { const { data: reminderCount, error: reminderError } = await supabase.rpc("schedule_draft_reminders", { p_league_id: league.id }); reminderMessage = reminderError ? " Draft reminders will need configuration first." : ` ${reminderCount || 0} reminder jobs scheduled.`; } setBusy(false); onUpdated({ ...league, ...data }); setMessage(`League details saved.${reminderMessage}`); }
  async function createInvite() { setBusy(true); const { data, error } = await supabase.rpc("create_league_invite", { p_league_id: league.id, p_email: null }); setBusy(false); if (error) return setMessage(error.message); const link = `${window.location.origin}?invite=${data.token}`; setInvite(link); try { await navigator.clipboard.writeText(link); setMessage("Invite link copied. It expires in 14 days."); } catch { setMessage("Invite link created. Copy it below."); } }
  return <div className="modal-backdrop"><section className="tools-modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">COMMISSIONER TOOLS</span><h2>League details & invites</h2><form className="form-stack" onSubmit={saveDetails}><label>League name<input value={name} onChange={(e) => setName(e.target.value)} required /></label><label>Season label<input value={season} onChange={(e) => setSeason(e.target.value)} /></label><label>Draft start date and time<input type="datetime-local" value={startsAt} onChange={(e) => setStartsAt(e.target.value)} /></label><label>Description<textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={3} /></label><label className="check-row"><input type="checkbox" checked={isPublic} onChange={(e) => setIsPublic(e.target.checked)} /> List this league publicly</label><button className="primary-button" disabled={busy}>{busy ? "Saving..." : "Save league details"}</button></form><hr /><h3>Invite coaches</h3><p className="muted">Share a single-use link. Coaches sign in with their own profile, then join this league.</p><button className="secondary-button" disabled={busy} onClick={createInvite}>Create & copy invite link</button>{invite && <input value={invite} readOnly style={{ marginTop: 10 }} onFocus={(e) => e.target.select()} />}{message && <p className="hub-message">{message}</p>}</section></div>;
}

export default function AuthGate() {
  const [supabase] = useState(() => createClient()); const [session, setSession] = useState(undefined); const [profile, setProfile] = useState(undefined); const [mode, setMode] = useState("sign_in"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [activeLeague, setActiveLeague] = useState(null); const [showTools, setShowTools] = useState(false);
  async function loadProfile(nextSession) { if (!nextSession) return setProfile(undefined); const { data } = await supabase.from("profiles").select("id, display_name, username").eq("id", nextSession.user.id).maybeSingle(); setProfile(data || null); }
  useEffect(() => { supabase.auth.getSession().then(({ data }) => { setSession(data.session); loadProfile(data.session); }); const { data: listener } = supabase.auth.onAuthStateChange((event, nextSession) => { setSession(nextSession); loadProfile(nextSession); if (event === "PASSWORD_RECOVERY") setMode("reset_password"); }); return () => listener.subscription.unsubscribe(); }, [supabase]);
  function changeMode(nextMode) { setMode(nextMode); setMessage(""); setPassword(""); setConfirmPassword(""); }
  async function submit(event) { event.preventDefault(); setBusy(true); setMessage(""); if (mode === "forgot_password") { const result = await supabase.auth.resetPasswordForEmail(email, { redirectTo: window.location.origin }); setBusy(false); return setMessage(result.error ? result.error.message : "If that email has an account, a password-reset link is on its way. Check your inbox and spam folder."); } if (mode === "reset_password") { if (password !== confirmPassword) { setBusy(false); return setMessage("The two passwords do not match."); } const result = await supabase.auth.updateUser({ password }); setBusy(false); return setMessage(result.error ? result.error.message : "Password updated. You are now signed in."); } if (mode === "sign_up" && password !== confirmPassword) { setBusy(false); return setMessage("The two passwords do not match."); } const result = mode === "sign_up" ? await supabase.auth.signUp({ email, password, options: { emailRedirectTo: window.location.origin } }) : await supabase.auth.signInWithPassword({ email, password }); setBusy(false); if (result.error) return setMessage(result.error.message); if (mode === "sign_up" && !result.data.session) setMessage("If that email can receive mail, a confirmation link is on its way. Check the address carefully, then check spam before trying again."); }
  if (session === undefined || (session && profile === undefined)) return <main style={{ minHeight: "100vh", display: "grid", placeItems: "center" }}>Loading DraftCenter...</main>;
  if (session && mode !== "reset_password") { if (!profile?.username) return <ProfileSetup supabase={supabase} user={session.user} onSaved={setProfile} />; if (!activeLeague) return <><div className="site-account"><span>@{profile.username}</span><button onClick={() => supabase.auth.signOut()}>Sign out</button></div><LeagueHub user={session.user} profile={profile} onOpenLeague={setActiveLeague} /></>; return <><div className="site-account"><button onClick={() => setActiveLeague(null)}>My leagues</button><span>@{profile.username}</span>{(activeLeague.role === "commissioner" || activeLeague.role === "co_commissioner") && <button onClick={() => setShowTools(true)}>League tools</button>}<button onClick={() => supabase.auth.signOut()}>Sign out</button></div><PokemonDraftLeague leagueId={activeLeague.id} leagueRole={activeLeague.role} profile={profile} />{showTools && <LeagueTools league={activeLeague} onClose={() => setShowTools(false)} onUpdated={setActiveLeague} />}</>; }
  const signingUp = mode === "sign_up"; const recovering = mode === "forgot_password"; const resetting = mode === "reset_password"; const title = resetting ? "Choose a new password" : recovering ? "Reset your password" : signingUp ? "Create your account" : "Welcome back";
  return <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 16, background: "radial-gradient(circle at top, #1d2857, #080b18 55%)" }}><section style={authPanel}><div className="eyebrow">DRAFTCENTER</div><h1 style={{ margin: "10px 0 6px" }}>{title}</h1><p style={{ margin: "0 0 22px", color: "#aeb7dc", lineHeight: 1.45 }}>{resetting ? "Enter and confirm a new password." : recovering ? "Enter your email and we will send a password-reset link." : signingUp ? "Use an email you can open now. We will ask you to confirm it before you can sign in." : "Sign in to create, join, and manage Pokemon Draft Leagues."}</p><form onSubmit={submit} style={{ display: "grid", gap: 13 }}>{!resetting && <label>Email<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" required autoComplete="email" style={inputStyle} /></label>}{!recovering && <label>{resetting ? "New password" : "Password"}<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" required minLength={6} autoComplete={signingUp || resetting ? "new-password" : "current-password"} style={inputStyle} /></label>}{(resetting || signingUp) && <label>{resetting ? "Confirm new password" : "Confirm password"}<input value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} type="password" required minLength={6} autoComplete="new-password" style={inputStyle} /></label>}{message && <p className="hub-message">{message}</p>}<button className="primary-button" disabled={busy}>{busy ? "Please wait..." : resetting ? "Update password" : recovering ? "Email reset link" : signingUp ? "Create account" : "Sign in"}</button></form>{recovering ? <button className="text-button" onClick={() => changeMode("sign_in")}>Back to sign in</button> : !resetting && <div className="auth-links">{!signingUp && <button className="text-button" onClick={() => changeMode("forgot_password")}>Forgot password?</button>}<button className="text-button" onClick={() => changeMode(signingUp ? "sign_in" : "sign_up")}>{signingUp ? "Already have an account? Sign in" : "New here? Create an account"}</button></div>}</section></main>;
}
