"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "../lib/supabase/client";
function when(value) { return value ? new Date(value).toLocaleString() : "Never"; }
function blank(kind,date) { return kind === "poll" ? { kind,date,question:"",options:["",""] } : kind === "quiz" ? { kind,date,prompt:"",hint:"",difficulty:"medium",accepted_answers:[""] } : { kind,date,question:"",topic:"human" }; }
export default function DailyThreeOperations() {
  const [data,setData]=useState(null); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("all"); const [editing,setEditing]=useState(null); const [busy,setBusy]=useState(false);
  async function session(){const supabase=createClient();const {data:auth}=await supabase.auth.getSession();return auth.session;}
  async function load(){setError("");const auth=await session();if(!auth)return setError("Sign in with an owner account.");const response=await fetch("/api/operations/daily-three",{headers:{Authorization:`Bearer ${auth.access_token}`}});const result=await response.json();if(!response.ok)return setError(result.error||"Daily Three operations could not load.");setData(result);}
  useEffect(()=>{load();},[]);
  async function save(event){event.preventDefault();setBusy(true);setMessage("");const auth=await session();const response=await fetch("/api/operations/daily-three",{method:"PUT",headers:{Authorization:`Bearer ${auth?.access_token||""}`,"Content-Type":"application/json"},body:JSON.stringify(editing)});const result=await response.json();setBusy(false);if(!response.ok)return setMessage(result.error||"That item could not be saved.");setEditing(null);setMessage("Editorial calendar saved.");await load();}
  const users=useMemo(()=>(data?.users||[]).filter((user)=>{if(filter==="today"&&user.last_activity_date!==data.today)return false;if(filter==="completed"&&!user.today.complete)return false;if(filter==="inactive"&&user.last_activity_at)return false;return `${user.display_name||""} ${user.username||""}`.toLowerCase().includes(query.toLowerCase());}),[data,filter,query]);
  if(error)return <main className="operations-shell"><a className="quiet-button" href="/operations">← League Operations</a><section className="operations-error"><h1>Daily Three</h1><p>{error}</p></section></main>;
  if(!data)return <main className="operations-shell"><p>Loading Daily Three…</p></main>;
  const tomorrow=new Date(`${data.today}T12:00:00Z`);tomorrow.setUTCDate(tomorrow.getUTCDate()+1);const firstFuture=tomorrow.toISOString().slice(0,10);const polls=new Map(data.editorial.polls.map((row)=>[row.poll_date,row]));const quizzes=new Map(data.editorial.quizzes.map((row)=>[row.quiz_date,row]));const questions=new Map(data.editorial.questions.map((row)=>[row.question_date,row]));const dates=[...new Set([...polls.keys(),...quizzes.keys(),...questions.keys()])].sort();
  function edit(kind,date,row){if(kind==="poll")setEditing({kind,date,question:row?.question||"",options:(row?.options||[]).map((option)=>option.label)});else if(kind==="quiz")setEditing({kind,date,prompt:row?.prompt||"",hint:row?.hint||"",difficulty:row?.difficulty||"medium",accepted_answers:row?.accepted_answers||[""]});else setEditing({kind,date,question:row?.question||"",topic:row?.topic||"human"});}
  return <main className="operations-shell"><nav className="public-page-nav"><a className="quiet-button" href="/operations">← League Operations</a><button className="quiet-button" onClick={load}>Refresh</button></nav><header className="operations-hero"><span className="eyebrow">OWNER ONLY · EDITORIAL CALENDAR</span><h1>Community daily content</h1><p>Preview and shape the Pokémon-only Daily Three, plus the separate human-first Question of the Day.</p><small>Today: {data.today}</small></header>
    <section className="editorial-actions"><button className="primary-button" onClick={()=>setEditing(blank("poll",firstFuture))}>Add poll</button><button className="secondary-button" onClick={()=>setEditing(blank("quiz",firstFuture))}>Add quiz</button><button className="quiet-button" onClick={()=>setEditing(blank("question",firstFuture))}>Add Question of the Day</button></section>{message&&<p className="hub-message">{message}</p>}
    <section className="editorial-calendar"><div className="editorial-head"><span>Date</span><span>Daily Three poll</span><span>Pokémon quiz</span><span>Question of the Day</span></div>{dates.map((date)=>{const poll=polls.get(date),quiz=quizzes.get(date),question=questions.get(date),locked=date<=data.today;return <article key={date}><strong>{date}{locked&&<small>Live · locked</small>}</strong><button disabled={locked} onClick={()=>edit("poll",date,poll)}><b>{poll?.question||"Add poll"}</b>{poll&&<small>{poll.options.map((o)=>o.label).join(" · ")}</small>}</button><button disabled={locked} onClick={()=>edit("quiz",date,quiz)}><b>{quiz?.prompt||"Add quiz"}</b>{quiz&&<small>{quiz.difficulty} · {(quiz.accepted_answers||[]).join(", ")}</small>}</button><button disabled={locked} onClick={()=>edit("question",date,question)}><b>{question?.question||"Add question"}</b>{question&&<small>{question.topic}</small>}</button></article>;})}</section>
    {editing&&<div className="modal-backdrop"><form className="editorial-modal" onSubmit={save}><button type="button" className="modal-close" onClick={()=>setEditing(null)}>×</button><span className="eyebrow">{editing.kind.replace("question","QUESTION OF THE DAY")}</span><h2>Edit future content</h2><label>Date<input type="date" min={firstFuture} value={editing.date} onChange={(e)=>setEditing({...editing,date:e.target.value})} required/></label>{editing.kind==="quiz"?<><label>Quiz prompt<textarea value={editing.prompt} onChange={(e)=>setEditing({...editing,prompt:e.target.value})} required/></label><label>Hint<input value={editing.hint} onChange={(e)=>setEditing({...editing,hint:e.target.value})}/></label><label>Difficulty<select value={editing.difficulty} onChange={(e)=>setEditing({...editing,difficulty:e.target.value})}>{["easy","medium","hard","expert"].map((v)=><option key={v}>{v}</option>)}</select></label><label>Accepted answers (one per line)<textarea value={editing.accepted_answers.join("\n")} onChange={(e)=>setEditing({...editing,accepted_answers:e.target.value.split("\n")})} required/></label></>:<><label>Question<textarea value={editing.question} onChange={(e)=>setEditing({...editing,question:e.target.value})} required/></label>{editing.kind==="poll"?<label>Choices (one per line)<textarea value={editing.options.join("\n")} onChange={(e)=>setEditing({...editing,options:e.target.value.split("\n")})} required/></label>:<label>Topic<select value={editing.topic} onChange={(e)=>setEditing({...editing,topic:e.target.value})}><option value="human">Human / community</option><option value="pokemon">Pokémon</option></select></label>}</>}<button className="primary-button" disabled={busy}>{busy?"Saving…":"Save to calendar"}</button></form></div>}
    <section className="operations-metrics"><article><strong>{data.totals.participants}</strong><span>Ever participated</span></article><article><strong>{data.totals.participated_today}</strong><span>Active today</span></article><article><strong>{data.totals.completed_today}</strong><span>Completed today</span></article><article><strong>{data.totals.completed_last_30_days}</strong><span>Completed in 30 days</span></article></section><section className="operations-controls"><div>{[["all","All users"],["today","Active today"],["completed","Completed today"],["inactive","Never participated"]].map(([key,label])=><button key={key} className={filter===key?"primary-button":"quiet-button"} onClick={()=>setFilter(key)}>{label}</button>)}</div><input placeholder="Search user" aria-label="Search users" value={query} onChange={(e)=>setQuery(e.target.value)}/></section><section className="daily-ops-table"><div className="daily-ops-head"><span>User</span><span>Today</span><span>Last activity</span><span>Last completion</span><span>30 days</span><span>All time</span></div>{users.map((user)=><article key={user.user_id}><div><strong>{user.display_name||user.username||"Unnamed user"}</strong><small>{user.username?`@${user.username}`:"Profile incomplete"}</small></div><div className="daily-ops-today"><span className={user.today.poll?"done":""}>Poll</span><span className={user.today.bracket?"done":""}>Bracket</span><span className={user.today.quiz?"done":""}>Quiz</span></div><span>{when(user.last_activity_at)}</span><span>{user.last_completed_date||"Never"}</span><strong>{user.completed_days_30}</strong><strong>{user.completed_days_total}</strong></article>)}</section></main>;
}
