"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "../lib/supabase/client";
function when(value) { return value ? new Date(value).toLocaleString() : "Never"; }
export default function DailyThreeOperations() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all");
  async function load() { const supabase = createClient(); const { data: auth } = await supabase.auth.getSession(); if (!auth.session) return setError("Sign in with an owner account."); const response = await fetch("/api/operations/daily-three", { headers: { Authorization: `Bearer ${auth.session.access_token}` } }); const result = await response.json(); if (!response.ok) return setError(result.error || "Daily Three participation could not load."); setData(result); }
  useEffect(() => { load(); }, []);
  const users = useMemo(() => (data?.users || []).filter((user) => { if (filter === "today" && user.last_activity_date !== data.today) return false; if (filter === "completed" && !user.today.complete) return false; if (filter === "inactive" && user.last_activity_at) return false; return `${user.display_name || ""} ${user.username || ""}`.toLowerCase().includes(query.toLowerCase()); }), [data, filter, query]);
  if (error) return <main className="operations-shell"><a className="quiet-button" href="/operations">← League Operations</a><section className="operations-error"><h1>Daily Three Participation</h1><p>{error}</p></section></main>;
  if (!data) return <main className="operations-shell"><p>Loading Daily Three participation…</p></main>;
  return <main className="operations-shell"><nav className="public-page-nav"><a className="quiet-button" href="/operations">← League Operations</a><button className="quiet-button" onClick={load}>Refresh</button></nav><header className="operations-hero"><span className="eyebrow">OWNER ONLY · PARTICIPATION</span><h1>Daily Three activity</h1><p>See whether registered users participate and when they last returned. Individual choices and quiz results stay private.</p><small>Today: {data.today}</small></header><section className="operations-metrics"><article><strong>{data.totals.participants}</strong><span>Ever participated</span></article><article><strong>{data.totals.participated_today}</strong><span>Active today</span></article><article><strong>{data.totals.completed_today}</strong><span>Completed today</span></article><article><strong>{data.totals.completed_last_30_days}</strong><span>Completed in 30 days</span></article></section><section className="operations-controls"><div>{[["all","All users"],["today","Active today"],["completed","Completed today"],["inactive","Never participated"]].map(([key,label]) => <button key={key} className={filter === key ? "primary-button" : "quiet-button"} onClick={() => setFilter(key)}>{label}</button>)}</div><input placeholder="Search user" aria-label="Search users" value={query} onChange={(event) => setQuery(event.target.value)} /></section><section className="daily-ops-table"><div className="daily-ops-head"><span>User</span><span>Today</span><span>Last activity</span><span>Last completion</span><span>30 days</span><span>All time</span></div>{users.map((user) => <article key={user.user_id}><div><strong>{user.display_name || user.username || "Unnamed user"}</strong><small>{user.username ? `@${user.username}` : "Profile incomplete"}</small></div><div className="daily-ops-today"><span className={user.today.poll ? "done" : ""}>Poll</span><span className={user.today.bracket ? "done" : ""}>Bracket</span><span className={user.today.quiz ? "done" : ""}>Quiz</span></div><span>{when(user.last_activity_at)}</span><span>{user.last_completed_date || "Never"}</span><strong>{user.completed_days_30}</strong><strong>{user.completed_days_total}</strong></article>)}</section></main>;
}
