"use client";
import { useState } from "react";
import { createClient } from "../lib/supabase/client";

export default function LeagueSupportRequestPanel({ league, context = {} }) {
  const [open,setOpen]=useState(false); const [category,setCategory]=useState("setup"); const [message,setMessage]=useState(""); const [includeDiagnostics,setIncludeDiagnostics]=useState(true); const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(event) { event.preventDefault(); setBusy(true); setStatus(""); const supabase=createClient(); const {data}=await supabase.auth.getSession(); if(!data.session){setBusy(false);return setStatus("Sign in again before submitting.");} const response=await fetch("/api/support/league-request",{method:"POST",headers:{Authorization:`Bearer ${data.session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({league_id:league.id,category,message,include_diagnostics:includeDiagnostics,context,page_path:window.location.pathname+window.location.search})}); const result=await response.json(); setBusy(false); if(!response.ok)return setStatus(result.error||"Support request could not be submitted."); setMessage(""); setStatus(result.owner_notified?"Request submitted. DraftCentral support was notified.":"Request saved. DraftCentral support will see it in League Operations."); }
  return <section className="support-access-panel"><h3>Get help with this league</h3><p className="muted">Send DraftCentral the league name, your description, and—only if you allow it—a small set of operational details. Messages, notebooks, rosters, and private account data are never attached.</p>{!open?<button type="button" className="secondary-button" onClick={()=>setOpen(true)}>Create support request</button>:<form className="form-stack" onSubmit={submit}><label>What do you need help with?<select value={category} onChange={(event)=>setCategory(event.target.value)}><option value="setup">League setup</option><option value="pricing">Pricing or tiers</option><option value="draft">Draft operation</option><option value="teams">Managers or teams</option><option value="results">Schedule or results</option><option value="notifications">Discord or notifications</option><option value="other">Something else</option></select></label><label>Describe the problem<textarea required minLength={10} maxLength={2000} rows={5} value={message} onChange={(event)=>setMessage(event.target.value)} placeholder="What were you trying to do, and what happened?" /></label><label className="check-label"><input type="checkbox" checked={includeDiagnostics} onChange={(event)=>setIncludeDiagnostics(event.target.checked)}/><span>Include safe diagnostics: save status, league status, draft type, team counts, the current page, browser type, and the latest displayed operational error.</span></label><details><summary>Review what will be included</summary><p className="muted">League: {league.name}<br/>Category: {category}<br/>Your description<br/>{includeDiagnostics?"The safe diagnostics listed above":"No diagnostics"}</p></details><div className="league-tool-compact-actions"><button className="primary-button" disabled={busy||message.trim().length<10}>{busy?"Submitting…":"Submit support request"}</button><button type="button" className="quiet-button" onClick={()=>setOpen(false)}>Cancel</button></div></form>}{status&&<p className="hub-message">{status}</p>}</section>;
}
