"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "../lib/supabase/client";

const severityOrder = { high: 0, medium: 1, low: 2 };
function when(value) { if (!value) return "Never"; return new Date(value).toLocaleString(); }

export default function OperationsDashboard() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [filter, setFilter] = useState("attention"); const [query, setQuery] = useState("");
  async function load() { setError(""); const supabase = createClient(); const { data: sessionData } = await supabase.auth.getSession(); if (!sessionData.session) return setError("Sign in with an owner account to open League Operations."); const response = await fetch("/api/operations/overview", { headers: { Authorization: `Bearer ${sessionData.session.access_token}` } }); const result = await response.json(); if (!response.ok) return setError(result.error || "League Operations could not load."); setData(result); }
  useEffect(() => { load(); }, []);
  const leagues = useMemo(() => (data?.leagues || []).filter((league) => { if (filter === "attention" && !league.warnings.length) return false; if (filter === "real" && league.is_practice) return false; if (filter === "practice" && !league.is_practice) return false; return `${league.name} ${league.commissioner}`.toLowerCase().includes(query.toLowerCase()); }).sort((a, b) => { const aPriority = Math.min(...a.warnings.map((w) => severityOrder[w.severity]), 9); const bPriority = Math.min(...b.warnings.map((w) => severityOrder[w.severity]), 9); return aPriority - bPriority || new Date(b.created_at) - new Date(a.created_at); }), [data, filter, query]);
  if (error) return <main className="operations-shell"><nav className="public-page-nav"><a className="quiet-button" href="/">DraftCenter</a></nav><section className="operations-error"><h1>League Operations</h1><p>{error}</p><button className="primary-button" onClick={load}>Try again</button></section></main>;
  if (!data) return <main className="operations-shell"><p>Loading League Operations…</p></main>;
  return <main className="operations-shell"><nav className="public-page-nav"><a className="quiet-button" href="/">DraftCenter</a><button className="quiet-button" onClick={load}>Refresh</button></nav><header className="operations-hero"><span className="eyebrow">OWNER ONLY</span><h1>League Operations</h1><p>See new leagues, upcoming drafts, operational risks, and support signals without entering private league content.</p><small>Updated {when(data.generated_at)}</small></header><section className="operations-metrics"><article><strong>{data.totals.leagues}</strong><span>Total leagues</span></article><article><strong>{data.totals.real}</strong><span>Real leagues</span></article><article><strong>{data.totals.needing_attention}</strong><span>Need attention</span></article><article className={data.totals.high_priority ? "danger" : ""}><strong>{data.totals.high_priority}</strong><span>High priority</span></article></section><section className="operations-controls"><div>{[["attention","Needs attention"],["real","Real leagues"],["practice","Practice"],["all","All"]].map(([key,label]) => <button key={key} className={filter === key ? "primary-button" : "quiet-button"} onClick={() => setFilter(key)}>{label}</button>)}</div><input aria-label="Search leagues" placeholder="Search league or commissioner" value={query} onChange={(event) => setQuery(event.target.value)} /></section><section className="operations-list">{leagues.length === 0 && <div className="operations-empty">No leagues match this view.</div>}{leagues.map((league) => <article className="operations-league" key={league.id}><header><div><span className="eyebrow">{league.is_practice ? "PRACTICE" : String(league.status || "setup").toUpperCase()}</span><h2>{league.name}</h2><p>{league.commissioner} · created {when(league.created_at)}</p></div><a className="quiet-button" href={`/?league=${encodeURIComponent(league.slug)}`}>Open league</a></header>{league.warnings.length > 0 && <div className="operations-warnings">{league.warnings.sort((a,b) => severityOrder[a.severity] - severityOrder[b.severity]).map((item) => <p className={`operations-warning ${item.severity}`} key={item.code}><strong>{item.severity}</strong><span>{item.text}</span></p>)}</div>}<dl><div><dt>Managers</dt><dd>{league.member_count}</dd></div><div><dt>Claimed teams</dt><dd>{league.claimed_team_count}/{league.team_count || "—"}</dd></div><div><dt>Draft</dt><dd>{when(league.draft_starts_at)}</dd></div><div><dt>Last activity</dt><dd>{when(league.last_activity_at)}</dd></div><div><dt>Last backup</dt><dd>{when(league.last_backup_at)}</dd></div><div><dt>Discord</dt><dd>{league.discord_connected ? "Connected" : "Not connected"}</dd></div></dl></article>)}</section></main>;
}
