"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "../lib/supabase/client";

const severityOrder = { high: 0, medium: 1, low: 2 };
function when(value) { return value ? new Date(value).toLocaleString() : "Never"; }
function supportScope(permission) { return permission === "pricing_edit" ? "Tier/pricing support" : "Read-only support"; }

export default function OperationsDashboard() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [filter, setFilter] = useState("attention"); const [query, setQuery] = useState(""); const [supportLeague, setSupportLeague] = useState(null); const [copyStatus, setCopyStatus] = useState("");
  async function load() { setError(""); const supabase = createClient(); const { data: sessionData } = await supabase.auth.getSession(); if (!sessionData.session) return setError("Sign in with an owner account to open League Operations."); const response = await fetch("/api/operations/overview", { headers: { Authorization: `Bearer ${sessionData.session.access_token}` } }); const result = await response.json(); if (!response.ok) return setError(result.error || "League Operations could not load."); setData(result); }
  async function updateSupportRequest(id, status) { const supabase=createClient(); const {data:sessionData}=await supabase.auth.getSession(); if(!sessionData.session)return; const response=await fetch(`/api/operations/support-request/${id}`,{method:"PATCH",headers:{Authorization:`Bearer ${sessionData.session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({status})}); if(response.ok)load(); }
  useEffect(() => { load(); }, []);
  const leagues = useMemo(() => (data?.leagues || []).filter((league) => { const archived = String(league.status) === "archived"; if (filter === "archived" && !archived) return false; if (filter !== "archived" && archived) return false; if (filter === "attention" && !league.warnings.length) return false; if (filter === "drafts" && !["drafting", "paused"].includes(league.lifecycle?.phase)) return false; if (filter === "real" && league.is_practice) return false; if (filter === "practice" && !league.is_practice) return false; return `${league.name} ${league.commissioner} ${league.lifecycle?.label || ""}`.toLowerCase().includes(query.toLowerCase()); }).sort((a, b) => { const aPriority = Math.min(...a.warnings.map((w) => severityOrder[w.severity]), 9); const bPriority = Math.min(...b.warnings.map((w) => severityOrder[w.severity]), 9); return aPriority - bPriority || new Date(b.lifecycle?.updated_at || b.created_at) - new Date(a.lifecycle?.updated_at || a.created_at); }), [data, filter, query]);
  function supportMessage(league) { return `Hi ${league.commissioner || "there"},\n\nI can review ${league.name}'s DraftCenter configuration without becoming a league member or receiving commissioner powers. If you want me to apply a completed pricing spreadsheet, the primary commissioner can approve the separate “Review and edit tiers/pricing” scope.\n\nPlease open ${league.name}, choose Commissioner Tools, and use Temporary support access to choose the scope and duration. You can revoke it at any time. Pricing support cannot change members, drafts, rosters, messages, results, or other league settings. DraftCenter creates a recovery point and audit entry before applying prices.`; }
  async function copyInstructions() { if (!supportLeague) return; try { await navigator.clipboard.writeText(supportMessage(supportLeague)); setCopyStatus("Instructions copied."); } catch { setCopyStatus("Copy was blocked. Select the message below and copy it manually."); } }
  if (error) return <main className="operations-shell"><nav className="public-page-nav"><a className="quiet-button" href="/">DraftCenter</a></nav><section className="operations-error"><h1>League Operations</h1><p>{error}</p><button className="primary-button" onClick={load}>Try again</button></section></main>;
  if (!data) return <main className="operations-shell"><p>Loading League Operations…</p></main>;
  return <main className="operations-shell">
    <nav className="public-page-nav"><a className="quiet-button" href="/">DraftCenter</a><a className="quiet-button" href="/operations/daily-three">Daily Three activity</a><button className="quiet-button" onClick={load}>Refresh</button></nav>
    <header className="operations-hero"><span className="eyebrow">OWNER ONLY</span><h1>League Operations</h1><p>Monitor league health without bypassing private-league membership. Configuration support requires commissioner-approved access.</p><small>Updated {when(data.generated_at)}</small></header>
    <section className="operations-user-summary" aria-labelledby="registered-users-title"><div><span className="eyebrow">AUTHENTICATION</span><h2 id="registered-users-title">Registered users</h2><p>Every DraftCenter account is counted, including people who joined through Discord. These totals show sign-in identities only; no emails or Discord usernames are exposed here.</p></div><div className="operations-metrics"><article><strong>{data.users?.total || 0}</strong><span>Total accounts</span></article><article><strong>{data.users?.discord || 0}</strong><span>Discord identity</span></article><article><strong>{data.users?.email || 0}</strong><span>Email identity</span></article><article><strong>{data.users?.both || 0}</strong><span>Email + Discord linked</span></article></div></section>
    <section className="operations-metrics"><article><strong>{data.totals.leagues}</strong><span>Active leagues</span></article><article><strong>{data.totals.archived || 0}</strong><span>Archived leagues</span></article><article><strong>{data.totals.real}</strong><span>Active real leagues</span></article><article><strong>{data.totals.drafting || 0}</strong><span>Active or paused drafts</span></article><article><strong>{data.totals.needing_attention}</strong><span>Need attention</span></article><article className={data.totals.high_priority ? "danger" : ""}><strong>{data.totals.high_priority}</strong><span>High priority</span></article><article className={data.totals.open_support_requests ? "danger" : ""}><strong>{data.totals.open_support_requests || 0}</strong><span>Support requests</span></article><article className={data.totals.errors_24h ? "danger" : ""}><strong>{data.totals.errors_24h || 0}</strong><span>System failures · 24 hours</span></article><article><strong>{data.totals.expected_rejections_24h || 0}</strong><span>Safety rejections · 24 hours</span></article></section>
    {(data.support_requests || []).length > 0 && <section className="operations-support-requests"><h2>Open support requests</h2>{data.support_requests.map((request) => <article key={request.id}><div><span className="eyebrow">{request.category} · {request.status.replaceAll("_"," ")}</span><h3>{request.league_name}</h3><p>{request.message}</p><small>{when(request.created_at)} · {request.diagnostics_included ? "safe diagnostics included" : "no diagnostics"}</small><div className="live-stream-actions">{request.status==="open"&&<button className="quiet-button" onClick={()=>updateSupportRequest(request.id,"in_progress")}>Mark in progress</button>}<button className="primary-button" onClick={()=>updateSupportRequest(request.id,"resolved")}>Resolve</button></div></div>{request.diagnostic_context?.last_error && <details><summary>Latest reported error</summary><pre>{request.diagnostic_context.last_error}</pre></details>}</article>)}</section>}
    {(data.operational_failures || []).length > 0 && <details className="operations-error-feed"><summary><strong>System failures</strong> · last 30 days</summary><p>Unexpected failures that may require investigation or a code, configuration, or provider fix.</p>{data.operational_failures.map((event)=><article key={event.id}><span className="eyebrow">{event.kind.replaceAll("_"," ")}</span><h3>{event.league_name}</h3><p>{event.message}</p><small>{when(event.occurred_at)} · {event.actor}</small></article>)}</details>}
    {(data.operational_rejections || []).length > 0 && <details className="operations-rejection-feed"><summary><strong>Expected safety rejections</strong> · last 30 days</summary><p>Permission checks, stale-session protection, duplicate picks, and other server safeguards working as intended.</p>{data.operational_rejections.map((event)=><article key={event.id}><span className="eyebrow">{event.kind.replaceAll("_"," ")}</span><h3>{event.league_name}</h3><p>{event.message}</p><small>{when(event.occurred_at)} · {event.actor}</small></article>)}</details>}
    <section className="operations-controls"><div>{[["attention","Needs attention"],["drafts","Drafts"],["real","Real leagues"],["practice","Practice"],["all","All active"],["archived","Archived"]].map(([key,label]) => <button key={key} className={filter === key ? "primary-button" : "quiet-button"} onClick={() => setFilter(key)}>{label}</button>)}</div><input aria-label="Search leagues" placeholder="Search league or commissioner" value={query} onChange={(event) => setQuery(event.target.value)} /></section>
    {filter !== "archived" && <section className="operations-lifecycle-board" aria-label="Draft lifecycle overview">
      <h2>Draft lifecycle</h2><p>See whether each draft is still being set up, live, manually paused, or complete without entering the league.</p>
      <div>{(data.leagues || []).filter((league) => ["drafting", "paused", "post_draft", "scheduled"].includes(league.lifecycle?.phase)).map((league) => <article className={league.lifecycle.phase} key={league.id}><div><strong>{league.name}</strong><span>{league.commissioner}</span></div><div><strong>{league.lifecycle.label}</strong><span>{league.lifecycle.detail}</span></div><small>Last lifecycle activity<br />{when(league.lifecycle.updated_at)}</small></article>)}</div>
    </section>}
    <section className="operations-list">{leagues.length === 0 && <div className="operations-empty">No leagues match this view.</div>}{leagues.map((league) => <article className="operations-league" key={league.id}><header><div><span className="eyebrow">{league.is_practice ? "PRACTICE" : String(league.status || "setup").toUpperCase()}</span><h2>{league.name}</h2><p>{league.commissioner} · created {when(league.created_at)}</p><small className={(league.owner_has_access || league.support_access) ? "operations-access granted" : "operations-access required"}>{league.owner_has_access ? `Your access: ${String(league.owner_role || "member").replaceAll("_", " ")}` : league.support_access ? `${supportScope(league.support_access.permission)} active until ${when(league.support_access.expires_at)}` : "Your access: support approval required"}</small></div>{league.owner_has_access ? <a className="quiet-button" href={`/?league=${encodeURIComponent(league.slug)}`}>Open league</a> : league.support_access ? <a className="primary-button" href={`/operations/league/${league.id}`}>Open {league.support_access.permission === "pricing_edit" ? "pricing support" : "read-only support"}</a> : <button className="quiet-button support-required-button" onClick={() => { setSupportLeague(league); setCopyStatus(""); }}>Support access required</button>}</header>{league.warnings.length > 0 && <div className="operations-warnings">{league.warnings.sort((a,b) => severityOrder[a.severity] - severityOrder[b.severity]).map((item) => <p className={`operations-warning ${item.severity}`} key={item.code}><strong>{item.severity}</strong><span>{item.text}</span></p>)}</div>}<dl><div><dt>Managers</dt><dd>{league.member_count}</dd></div><div><dt>Claimed teams</dt><dd>{league.claimed_team_count}/{league.team_count || "—"}</dd></div><div><dt>Draft</dt><dd>{when(league.draft_starts_at)}</dd></div><div><dt>Last activity</dt><dd>{when(league.last_activity_at)}</dd></div><div><dt>Last recovery</dt><dd>{when(league.last_backup_at)}</dd></div><div><dt>Discord</dt><dd>{league.discord_connected ? "Connected" : "Not connected"}</dd></div></dl></article>)}</section>
    {supportLeague && <div className="modal-backdrop"><section className="tools-modal support-access-modal" role="dialog" aria-modal="true" aria-labelledby="support-access-title"><button className="modal-close" onClick={() => setSupportLeague(null)}>×</button><span className="eyebrow">COMMISSIONER APPROVAL</span><h2 id="support-access-title">Support access required</h2><p>Send these instructions to {supportLeague.commissioner || "the commissioner"}. Their approval creates a separate, expiring support session; it does not add you as a manager or co-commissioner.</p><ol><li>Open the league in DraftCenter.</li><li>Open <strong>Commissioner Tools</strong>.</li><li>Find <strong>Temporary support access</strong>.</li><li>Choose <strong>Review only</strong> or, for the primary commissioner, <strong>Review and edit tiers/pricing</strong>.</li><li>Choose a duration, approve it, and then refresh Operations.</li></ol><textarea readOnly rows={10} value={supportMessage(supportLeague)} aria-label="Support invitation instructions" /><div className="live-stream-actions"><button className="primary-button" onClick={copyInstructions}>Copy message for commissioner</button><button className="quiet-button" onClick={() => setSupportLeague(null)}>Close</button></div>{copyStatus && <p className="hub-message">{copyStatus}</p>}</section></div>}
  </main>;
}
