"use client";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "../lib/supabase/client";

const tournamentError=(error)=>error?.code==="PGRST202"?"Tournaments are not enabled in this environment yet.":error?.message||"Tournament service is unavailable. Please try again.";

function MatchCard({match,entrants,submission,canReport,isOwner,onRefresh,supabase}){const [scoreA,setScoreA]=useState(match.games_a??"");const [scoreB,setScoreB]=useState(match.games_b??"");const [replay,setReplay]=useState(match.replay_urls?.[0]||"");const [mvp,setMvp]=useState(match.mvp||"");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const a=entrants.get(match.entrant_a_id);const b=entrants.get(match.entrant_b_id);const wins=Math.ceil(match.best_of/2);
  async function report(event){event.preventDefault();setBusy(true);setMessage("");const {error}=await supabase.rpc("submit_tournament_result",{p_match_id:match.id,p_expected_revision:match.revision,p_games_a:Number(scoreA),p_games_b:Number(scoreB),p_replay_urls:replay.trim()?[replay.trim()]:[],p_mvp:mvp.trim()||null});setBusy(false);if(error)return setMessage(error.message);onRefresh();}
  async function confirm(){setBusy(true);setMessage("");const {error}=await supabase.rpc("confirm_tournament_result",{p_submission_id:submission.id,p_expected_match_revision:match.revision});setBusy(false);if(error)return setMessage(error.message);onRefresh();}
  async function reject(){setBusy(true);setMessage("");const {error}=await supabase.rpc("reject_tournament_result",{p_submission_id:submission.id,p_expected_match_revision:match.revision});setBusy(false);if(error)return setMessage(error.message);onRefresh();}
  async function correct(event){event.preventDefault();if(!window.confirm("Correct this result and update its next bracket slot?"))return;setBusy(true);setMessage("");const {error}=await supabase.rpc("correct_tournament_result",{p_match_id:match.id,p_expected_revision:match.revision,p_games_a:Number(scoreA),p_games_b:Number(scoreB),p_replay_urls:replay.trim()?[replay.trim()]:[],p_mvp:mvp.trim()||null});setBusy(false);if(error)return setMessage(error.message);onRefresh();}
  return <article className={`tournament-match is-${match.status}`}><header><span>Match {match.match_number}</span><b>{match.status}</b></header><div className={`tournament-match-side ${match.winner_id===a?.id?"winner":""}`}><span>{a?`#${a.seed}`:"—"}</span><strong>{a?.display_name||"TBD"}</strong>{match.games_a!=null&&<b>{match.games_a}</b>}</div><div className={`tournament-match-side ${match.winner_id===b?.id?"winner":""}`}><span>{b?`#${b.seed}`:"—"}</span><strong>{b?.display_name||"TBD"}</strong>{match.games_b!=null&&<b>{match.games_b}</b>}</div>{match.mvp&&<small>MVP: {match.mvp}</small>}
    {match.status==="ready"&&canReport&&<form className="tournament-report" onSubmit={report}><div><label>{a?.display_name} games<input type="number" min="0" max={wins} required value={scoreA} onChange={(e)=>setScoreA(e.target.value)}/></label><label>{b?.display_name} games<input type="number" min="0" max={wins} required value={scoreB} onChange={(e)=>setScoreB(e.target.value)}/></label></div><input type="url" placeholder="Optional replay https://…" value={replay} onChange={(e)=>setReplay(e.target.value)}/><input maxLength={120} placeholder="Optional MVP" value={mvp} onChange={(e)=>setMvp(e.target.value)}/><button className="secondary-button" disabled={busy}>{busy?"Reporting…":"Report result"}</button></form>}
    {match.status==="reported"&&submission&&<div className="tournament-confirm"><p>{submission.games_a}–{submission.games_b} reported{submission.submitted_by_me?" — waiting for your opponent.":" — confirm this result?"}</p>{(!submission.submitted_by_me||isOwner)&&<div><button className="primary-button" disabled={busy} onClick={confirm}>{busy?"Confirming…":"Confirm & advance"}</button><button className="quiet-button" disabled={busy} onClick={reject}>Reject report</button></div>}</div>}{match.status==="complete"&&isOwner&&<details className="tournament-correction"><summary>Correct result</summary><form className="tournament-report" onSubmit={correct}><div><label>{a?.display_name} games<input type="number" min="0" max={wins} required value={scoreA} onChange={(e)=>setScoreA(e.target.value)}/></label><label>{b?.display_name} games<input type="number" min="0" max={wins} required value={scoreB} onChange={(e)=>setScoreB(e.target.value)}/></label></div><input type="url" placeholder="Optional replay https://…" value={replay} onChange={(e)=>setReplay(e.target.value)}/><input maxLength={120} placeholder="Optional MVP" value={mvp} onChange={(e)=>setMvp(e.target.value)}/><button className="quiet-button" disabled={busy}>{busy?"Correcting…":"Save correction"}</button></form></details>}{message&&<p className="hub-message">{message}</p>}</article>;
}

export default function TournamentWorkspace({slug}){const [supabase]=useState(()=>createClient());const [user,setUser]=useState(undefined);const [personalTeams,setPersonalTeams]=useState([]);const [selectedTeam,setSelectedTeam]=useState("");const [workspace,setWorkspace]=useState(null);const [message,setMessage]=useState("Loading tournament…");const [name,setName]=useState("");const [busy,setBusy]=useState(false);const [inviteCode,setInviteCode]=useState(null);const [inviteReady,setInviteReady]=useState(false);
  async function load(){const {data,error}=await supabase.rpc("get_tournament_workspace",{p_slug:slug,p_access_code:inviteCode});if(error){setMessage(tournamentError(error));setWorkspace(null);}else if(!data){setMessage("This tournament is private or unavailable.");setWorkspace(null);}else{setWorkspace(data);setMessage("");}}
  useEffect(()=>{const code=new URLSearchParams(window.location.hash.slice(1)).get("code");setInviteCode(code&&/^[0-9a-f]{16}$/.test(code)?code:null);setInviteReady(true);},[]);
  useEffect(()=>{if(!inviteReady)return;supabase.auth.getUser().then(async({data})=>{const next=data.user||null;setUser(next);if(next){const result=await supabase.from("personal_teams").select("id,team_name").eq("owner_id",next.id).eq("archived",false).order("updated_at",{ascending:false});if(!result.error)setPersonalTeams(result.data||[]);}});load();},[supabase,slug,inviteCode,inviteReady]);
  const entrants=useMemo(()=>new Map((workspace?.entrants||[]).map((entrant)=>[entrant.id,entrant])),[workspace]);const me=workspace?.entrants?.find((entrant)=>entrant.is_me);const rounds=useMemo(()=>{const grouped=new Map();for(const match of workspace?.matches||[]){if(!grouped.has(match.round_number))grouped.set(match.round_number,[]);grouped.get(match.round_number).push(match);}return [...grouped.entries()];},[workspace]);
  async function join(event){event.preventDefault();setBusy(true);const {error}=await supabase.rpc("join_tournament",{p_tournament_id:workspace.tournament.id,p_display_name:name,p_registered_team_id:selectedTeam||null,p_access_code:inviteCode});setBusy(false);if(error)return setMessage(error.message);setName("");setSelectedTeam("");load();}
  async function copyInvite(){setBusy(true);setMessage("");let code=inviteCode;if(!code){const {data,error}=await supabase.rpc("rotate_tournament_registration_code",{p_tournament_id:workspace.tournament.id});if(error){setBusy(false);return setMessage(error.message);}code=data;setInviteCode(data);window.history.replaceState(null,"",`/tournaments/${slug}#code=${encodeURIComponent(data)}`);}const link=`${window.location.origin}/tournaments/${slug}#code=${encodeURIComponent(code)}`;try{await navigator.clipboard.writeText(link);setMessage("Private registration link copied. Replacing the link will invalidate this one.");}catch{setMessage("Copy the private registration link from your browser address bar.");}setBusy(false);}
  async function seed(entrant,value){if(!value)return;setBusy(true);const {error}=await supabase.rpc("set_tournament_seed",{p_tournament_id:workspace.tournament.id,p_entrant_id:entrant.id,p_seed:Number(value)});setBusy(false);if(error)return setMessage(error.message);load();}
  async function shuffleSeeds(){if(!window.confirm("Shuffle every entrant into a new deterministic seed order?"))return;setBusy(true);setMessage("");const {error}=await supabase.rpc("randomize_tournament_seeds",{p_tournament_id:workspace.tournament.id,p_random_key:crypto.randomUUID()});setBusy(false);if(error)return setMessage(error.message);load();}
  async function lock(){if(!window.confirm("Lock registration and generate the bracket? Entrants cannot join afterward."))return;setBusy(true);const {error}=await supabase.rpc("lock_single_elimination_tournament",{p_tournament_id:workspace.tournament.id});setBusy(false);if(error)return setMessage(error.message);load();}
  async function archive(){if(!window.confirm("Archive this tournament? Its bracket and history will remain read-only."))return;setBusy(true);const {error}=await supabase.rpc("archive_tournament",{p_tournament_id:workspace.tournament.id});setBusy(false);if(error)return setMessage(error.message);load();}
  if(!workspace)return <main className="tournament-shell"><a className="quiet-button" href="/tournaments">← Tournaments</a><section className="tournament-panel"><p>{message}</p></section></main>;const tournament=workspace.tournament;
  return <main className="tournament-shell"><header className="tournament-detail-hero"><a className="quiet-button" href="/tournaments">← Tournaments</a><span className="eyebrow">{tournament.status} · {tournament.visibility}</span><h1>{tournament.name}</h1><p>{tournament.description||"Standalone single-elimination tournament"}</p><div><span>Best of {tournament.best_of}</span><span>{workspace.entrants.length} / {tournament.entrant_limit} entrants</span>{tournament.is_owner&&tournament.visibility==="private"&&tournament.status==="registration"&&<button className="quiet-button" disabled={busy} onClick={copyInvite}>{inviteCode?"Copy private registration link":"Create private registration link"}</button>}{tournament.is_owner&&["registration","complete"].includes(tournament.status)&&<button className="quiet-button" disabled={busy} onClick={archive}>Archive</button>}</div></header>{message&&<p className="hub-message">{message}</p>}
    {tournament.status==="registration"&&<section className="tournament-panel"><div className="section-heading"><div><span className="eyebrow">REGISTRATION</span><h2>Entrants</h2></div>{tournament.is_owner&&workspace.entrants.length>=2&&<div className="tournament-owner-actions"><button className="quiet-button" disabled={busy} onClick={shuffleSeeds}>Shuffle seeds</button><button className="primary-button" disabled={busy} onClick={lock}>Lock & build bracket</button></div>}</div>{!me&&(user?<form className="tournament-join" onSubmit={join}><input required maxLength={100} placeholder="Tournament display name" value={name} onChange={(e)=>setName(e.target.value)}/>{personalTeams.length>0&&<select aria-label="Saved team" value={selectedTeam} onChange={(e)=>setSelectedTeam(e.target.value)}><option value="">No saved team</option>{personalTeams.map((team)=><option key={team.id} value={team.id}>{team.team_name}</option>)}</select>}<button className="secondary-button" disabled={busy}>Register</button></form>:<p className="muted">Sign in from the DraftCenter home page to register.</p>)}<div className="tournament-entrant-list">{workspace.entrants.map((entrant)=><article key={entrant.id}><strong>{entrant.display_name}</strong>{tournament.is_owner?<label>Seed<input key={`${entrant.id}-${entrant.seed??"none"}`} type="number" min="1" max={workspace.entrants.length} defaultValue={entrant.seed||""} onBlur={(e)=>seed(entrant,e.target.value)}/></label>:<span>{entrant.seed?`Seed ${entrant.seed}`:"Awaiting seed"}</span>}</article>)}</div></section>}
    {rounds.length>0&&<section className="tournament-bracket"><div className="section-heading"><div><span className="eyebrow">SINGLE ELIMINATION</span><h2>Bracket</h2></div><button className="quiet-button" onClick={load}>Refresh</button></div><div className="tournament-rounds">{rounds.map(([round,matches])=><section key={round}><h3>{matches.length===1?"Final":`Round ${round}`}</h3>{matches.map((match)=>{const submission=workspace.submissions.find((item)=>item.match_id===match.id);const involved=me&&[match.entrant_a_id,match.entrant_b_id].includes(me.id);return <MatchCard key={match.id} match={match} entrants={entrants} submission={submission} canReport={Boolean(involved||tournament.is_owner)} isOwner={tournament.is_owner} onRefresh={load} supabase={supabase}/>;})}</section>)}</div></section>}
    {tournament.rules&&<section className="tournament-panel"><span className="eyebrow">RULES</span><h2>Tournament rules</h2><p className="tournament-rules">{tournament.rules}</p></section>}</main>;
}
